# Generated by Django 4.2.11 on 2026-06-04 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.CharField(max_length=100, unique=True)),
                ("contract_name", models.CharField(max_length=255)),
                ("vendor_name", models.CharField(max_length=255)),
                ("client_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("raw_terms", models.TextField(help_text="Raw contract terms text")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "s3_document_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("rule_type", models.CharField(max_length=50)),
                (
                    "condition_json",
                    models.TextField(help_text="JSON conditions for rule validation"),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action to take when rule is violated", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PricingTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("variable", "Variable"),
                            ("tiered", "Tiered"),
                            ("usage", "Usage-Based"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="fixed",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "volume_tier_min",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "volume_tier_max",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                ("billing_frequency", models.CharField(blank=True, max_length=50)),
                ("payment_terms", models.CharField(blank=True, max_length=255)),
                (
                    "minimum_commitment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_terms",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_contract_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("pricing_term_count", models.IntegerField(default=0)),
                (
                    "highest_discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("currency_diversity", models.IntegerField(default=0)),
                (
                    "recurring_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "one_time_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="contracts.contract",
                    ),
                ),
            ],
        ),
    ]
