# Generated by Django 4.2.11 on 2026-06-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingterm",
            name="unit",
            field=models.CharField(blank=True, default="unit", max_length=50),
        ),
    ]
